import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'

import { initializeApp } from "firebase/app";
import { getMessaging, getToken } from "firebase/messaging";

export default function Home() {

  const [token, setToken] = useState();

  useEffect(() => {

    function requestPermission() {
      console.log('Requesting permission...');
      Notification.requestPermission().then((permission) => {
        if (permission === 'granted') {
          console.log('Notification permission granted.');
        }
      })
    }

    requestPermission();

    // Import the functions you need from the SDKs you need
    // TODO: Add SDKs for Firebase products that you want to use
    // https://firebase.google.com/docs/web/setup#available-libraries

    // Your web app's Firebase configuration
    const firebaseConfig = {
      apiKey:process.env.NEXT_PUBLIC_apiKey,
      authDomain:process.env.NEXT_PUBLIC_authDomain,
      projectId:process.env.NEXT_PUBLIC_projectId,
      storageBucket:process.env.NEXT_PUBLIC_storageBucket,
      messagingSenderId:process.env.NEXT_PUBLIC_messagingSenderId,
      appId:process.env.NEXT_PUBLIC_appId
    };

    // Initialize Firebase
    const app = initializeApp(firebaseConfig);
    // Initialize Firebase Cloud Messaging and get a reference to the service
    const messaging = getMessaging(app);
    // Add the public key generated from the console here.
    getToken(messaging, {vapidKey: process.env.NEXT_PUBLIC_vapidKey})
      .then((currentToken) => {
        if (currentToken) {
          // Send the token to your server and update the UI if necessary
          setToken(currentToken)
          // ...
        } else {
          // Show permission request UI
          console.log('No registration token available. Request permission to generate one.');
          // ...
        }
      })

  }, [])

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1>Notificaciones</h1>
        {
          token && <p>{token}</p>
        }
      </main>
    </>
  )
}
